-- The reference food table, from a published composition database rather than
-- the two dozen rows that got the app this far.
--
-- Everything in this epic — energy on a card, macros on a meal, a weekly
-- target, a chart — is arithmetic on these numbers. With 24 foods, almost
-- every ingredient fell through to a flat guess marked "estimated"; the guess
-- and the flag stay, because no table covers everything somebody can write in
-- a recipe, but they become rare instead of usual.
--
-- Rows are not written here. They are imported from the CSVs under
-- `resources/food/`, which are generated by `tools/food-table/build.py` and
-- re-imported whenever their checksum changes — so following an upstream
-- release is a regenerate and a diff, not a hand-edited migration.

CREATE TABLE foods (
    id BIGSERIAL PRIMARY KEY,
    -- Which published table a row came from. A second source later means a
    -- second value here, and the ability to re-import one without the other.
    source VARCHAR(20) NOT NULL,
    source_ref VARCHAR(40) NOT NULL,
    category VARCHAR(160),
    aisle VARCHAR(20) NOT NULL DEFAULT 'OTHER',
    -- Per 100 g / 100 ml, which is what `NutritionService.factorFor` expects.
    kcal NUMERIC(8, 2) NOT NULL,
    protein_g NUMERIC(8, 2),
    carbs_g NUMERIC(8, 2),
    fat_g NUMERIC(8, 2),
    fibre_g NUMERIC(8, 2),
    sugars_g NUMERIC(8, 2),
    salt_g NUMERIC(8, 2),
    UNIQUE (source, source_ref)
);

-- Names and synonyms, in every language the app speaks. Matching happens on
-- `normalised`, which is the name lowercased, unaccented and depunctuated —
-- stored rather than computed, so the index is usable and the rule has one
-- implementation on each side rather than one per query.
CREATE TABLE food_names (
    id BIGSERIAL PRIMARY KEY,
    food_id BIGINT NOT NULL REFERENCES foods(id) ON DELETE CASCADE,
    locale VARCHAR(5) NOT NULL,
    name VARCHAR(255) NOT NULL,
    normalised VARCHAR(255) NOT NULL,
    UNIQUE (food_id, locale, normalised)
);

CREATE INDEX idx_food_names_normalised ON food_names (normalised);

-- Everything past the macros. A table rather than columns because the set
-- depends on the source and will change with it, and because a screen only
-- ever asks for the handful it shows.
CREATE TABLE food_micronutrients (
    food_id BIGINT NOT NULL REFERENCES foods(id) ON DELETE CASCADE,
    code VARCHAR(30) NOT NULL,
    amount NUMERIC(12, 3) NOT NULL,
    unit VARCHAR(5) NOT NULL,
    PRIMARY KEY (food_id, code)
);

-- What was imported, and from which version of the file. The importer compares
-- the checksum and does nothing when it matches, so booting is cheap and
-- refreshing is just a changed file.
CREATE TABLE food_imports (
    id BIGSERIAL PRIMARY KEY,
    source VARCHAR(20) NOT NULL UNIQUE,
    checksum VARCHAR(64) NOT NULL,
    foods INTEGER NOT NULL,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The 24 hand-written rows are superseded. Their aisle lives on `foods` now,
-- and the shopping list reads it from there.
DROP TABLE food_nutrition;
