-- Where a recipe's photo came from: UPLOADED by hand, IMPORTED with the
-- page, or GENERATED by an image model for a dish a model wrote. Like
-- `origin`, a provenance the code writes and the editor never sends — the
-- screen says "illustration" only because the code knows it is one.
ALTER TABLE recipes ADD COLUMN photo_origin VARCHAR(16);

UPDATE recipes SET photo_origin = 'IMPORTED' WHERE photo_path IS NOT NULL AND source_url IS NOT NULL;
UPDATE recipes SET photo_origin = 'UPLOADED' WHERE photo_path IS NOT NULL AND photo_origin IS NULL;
